### ISSUE TITLE
Make cert trimmed_subjects always be lowercase

### ISSUE THREAD

**Issue by dav3r** [cisagov/cyhy-ct-logs#3]
Querying certs would be very much simplified if we could rely on trimmed_subjects (in certs collection) being lowercase.

**Comment by felddy** [comment]
I think this was implemented: 
https://github.com/cisagov/cyhy-ct-logs/blob/e3aa4680a80faa7e2f76744b283bcfcbf04659aa/src/admiral/util/domains.py#L14

@dav3r, Let me know if this satisfied this issue.

**Comment by dav3r** [comment]
@felddy Yes, that is all good now - closing out this issue - thanks!
